package com.henry.dcoll.message;

public enum MessageType {
	DLIST_UNION,
	DLIST_SEPARATION,
	METHOD_INVOCATION,
	ADDITION_INTO_LOCAL_LIST,
	ADDITION_INTO_REMOTE_LIST,
	REMOVAL_FROM_REMOTE_LIST,
	REMOVAL_FROM_LOCAL_LIST_BY_INDEX,
	REMOVAL_FROM_LOCAL_LIST_BY_OBJECT;
}
